services:
  - type: web
    name: fopofo-chabot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHONPATH
        value: .
    plan: free
